theme: minima
title: Iridis Alpha Theory
description: >
  It's not really a theory.

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: devto,          user_url: "https://dev.to/jekyll" }
    - { platform: twitter,        user_url: "https://twitter.com/mwenge" }
    - { platform: github,         user_url: "https://github.com/mwenge/iatheory" }
    
plugins:
  - jekyll-feed
  - jekyll-seo-tag
