theme: minima
title: Iridis Alpha Theory
description: >
  It's not really a theory.

skin: solarized-dark

minima:
   social_links:
     - { platform: twitter,        user_url: "https://twitter.com/mwenge" }
     - { platform: github,         user_url: "https://github.com/mwenge/iatheory" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
